// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lboqkakzknmpzkejtefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxib3FrYWt6a25tcHprZWp0ZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMTQ4OTksImV4cCI6MjA4NTc5MDg5OX0.zEnu4RxE6NyqJEXhhJFChFfua2RMdAwHCtGjb5_tDEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});